CLASS LCL_ZBC425_CLASS_IMP_ENH_11 DEFINITION DEFERRED.
CLASS CL_BC425_CUSTOMER_11 DEFINITION LOCAL FRIENDS LCL_ZBC425_CLASS_IMP_ENH_11.
CLASS LCL_ZBC425_CLASS_IMP_ENH_11 DEFINITION.
PUBLIC SECTION.
CLASS-DATA OBJ TYPE REF TO LCL_ZBC425_CLASS_IMP_ENH_11. "#EC NEEDED
DATA CORE_OBJECT TYPE REF TO CL_BC425_CUSTOMER_11 . "#EC NEEDED
 INTERFACES  IPO_ZBC425_CLASS_IMP_ENH_11.
  METHODS:
   CONSTRUCTOR IMPORTING CORE_OBJECT
     TYPE REF TO CL_BC425_CUSTOMER_11 OPTIONAL.
ENDCLASS.
CLASS LCL_ZBC425_CLASS_IMP_ENH_11 IMPLEMENTATION.
METHOD CONSTRUCTOR.
  ME->CORE_OBJECT = CORE_OBJECT.
ENDMETHOD.

METHOD IPO_ZBC425_CLASS_IMP_ENH_11~DISPLAY.
*"------------------------------------------------------------------------*
*" Declaration of POST-method, do not insert any comments here please!
*"
*"methods DISPLAY .
*"------------------------------------------------------------------------*
WRITE:/ 'Birthday:', core_object->mv_birthday.
 WRITE:/ 'City:', core_object->mv_city.
ENDMETHOD.
ENDCLASS.
